const reactions = [
  "Took your advice, it worked, but then it caused another problem, hope you can take a look at it as well.",
  "Really kind people explain everything in details, so I think that admin of this blog is really kind person.",
  "Traveling in India was amazing, I have seen so many magnificent building, India has really rich culture and ancient as well.",
  "Summer, kind of love it kind of hate it, I have mixed feelings about it.",
  "Is there any way to increase quality of the image? I need help with it asap.",
  "Who is your favorite singer? Come on guys, list some names, let's find people with the same taste in the music.",
  "Interesting guide author, but I prefer RPG games more than puzzle games.",
  "I do not like direction where global economy is heading, I feel like there is going to be huge crisis soon and it scares me.",
  "Best way to spend your time is to take a walk in the woods, it brings peace of mind and you feel rejuvenated.",
  "What a pleasant surprise, new post and new guides for me.",
  "New authors are awesome I see, keep it up gentlemen good work!",
  "Which bird can fly higher than anyone else? I believe it is Albatross right? Amazing bird indeed.",
  "I like a new character, I also enjoyed new attack combinations and special moves, SSF 2 is my favorite game again!",
  "I think if I had another chance, another opportunity I would have chosen a different profession, for example, writer.",
  "Competition is awesome thing, but it can be very fierce sometimes. Overall, without competition, we would still be trapped in the Stone Age…",
  "All my friends are in relationship, is there something wrong with me?",
  "Oh, no dear, you do not have to take my word for it, there are countless sources that say exactly the same thing.",
  "I am not going to describe it, not because I do not want to, but because I have no idea how to express or describe this feeling with words.",
  "Childhood memories are always brightest ones, they are there for you for the rest of your life and they shine upon you for eternity.",
  "Do you believe in magic? I do, I think that strong faith in something can materialize our feelings and thoughts.",
  "You are right, it is true that fixing requires step by step approach.",
  "Question I have is simple, why your solution did not work in my case?",
  "What an amazing writing, awesome illustrations, awesome paragraphs. I always enjoyed your articles.What an amazing writing, awesome illustrations, awesome paragraphs. I always enjoyed your articles.",
  "I really love car games and racing games, cool vehicles, nitro boosters, etc. Racing games are life!",
  "I really love high quality music, I want to hear from you some suggestions, about which speakers are best right now.",
  "I really enjoy more spending free time at home, watching TV or playing computer games is my thing.",
  "I can drive 20 miles, walk 500 feet. Turn around and before I know it, I'd be back home. Or would I? I'm not sure but that's just how it is.",
  "So the other day I got flamed hard as hell in COD and do you know what was a reason? Being good…",
  "Most of you lack morality and higher values, it is painful to watch at it.",
  "I am little bit of worried, I have read somewhere that mobile phones can cause harm to health, is it for real?",
  "I like rude people at some point, they always say what they have in mind, at least you can know what to expect from them.",
  "I have feelings and emotions like any other human being, but their role in my decision making is nearly zero.",
  "In fourth paragraph you have spelling mistake, fix it please, it hurts my sight.",
  "Ready, set, go... it is time to have some amazing gaming experience...",
  "Violence is society is way too high, it is now scary to go outside and it is dangerous.",
  "After all these years, after all of this struggle and suffering, I can finally find peace and enjoy my solitude.",
  "I just cant stop listening to ambient music, I cant get enough of it, ambient music is a gift of God.",
  "I switched to Bluetooth headset a long time ago, it is a lot more comfortable than wired headphones.",
  "What is your favorite number? Mine is seven, some people say that numbers have magical powers and they can tell a lot about personality.",
  "Yet another epic article from you, once again on point, and once again useful.",
];

module.exports = reactions;
