const thoughts = [
  "Which movie was the funniest of all? I think Very Scary Movie was super hilarious.",
  "So according to statistics humans can survive without air for three minutes. I am pretty sure that my maximum is below one minute.",
  "I used to play with warrior in WoW, was really hard, especially key bindings : D",
  "So if I got your words correctly, you want to do nothing and earn respect anyway? It doesnt work this way.",
  "Any COD players around? Lets make party and play together guys.",
  "I don't love to risk in life, I love to make calculated decisions, this side of mine has both good consequences and bad ones as well.",
  "You do your job and I will do mine, it is better this way.",
  "Lack of time is very problematic thing, on the other hand, you have to work in order to feed your family.",
  "We are expanding our business, we are hiring more people and we are working on our new big projects.",
  "Some people have such an amazing talent for trolling...",
  "Watched yet another anime show yesterday, whole 20 episodes per one day, I still got it : D",
  "What is Bitcoin? Can someone give me simple explanation? I have no clue...",
  "My hair is kind of dry, I wonder which shampoo can fix this… Any suggestions? Maybe someone knows?",
  "What is your favorite snack? I love potato chips very much, but I always try to keep my distance with it, this snack is dangerous and bad for your health, but it is so delicious…",
  "Which apple do you love the most? Red one or green one? I personally admire the green one.",
  "I just turned notifications off a couple of minutes ago and I still get them, is this some kind of PC virus or something?",
  "Anyone knows some good idea to increase MMR fast in Dota?",
  "Can you imagine how helpful it was? Fixed problem instantly after suffering from it for months.",
  "Be careful how you choose your friends, the wrong choice can have bad consequences.",
  "I love to hang different paintings on my walls, I love art and I admire high-quality work.",
  "Is it okay to find yourself in loneliness? To admire loneliness and to pursue it?",
  "I salute all the fellow gamers out there who don't rage and just play their role without trash talking.",
  "I had so many funny incidents with hotels during my travelling, kind of embarrassing ones as well.",
  "Do people actually send envelopes these days? E-mail is used in the most cases.",
  "They are right, usually they make mistakes but in this case, they are 100% right. Hard to admit it : D",
  "Partly right partly wrong, do not get me wrong, we all get same results here, finding solution seems impossible.",
  "Take off your pink glasses and look at the world with a realistic view, this world is full of violence…",
  "I love to watch different short animation movies, sometimes they are sad, and sometimes they are funny…",
  "Some countries are very lucky to have the sea, I really love swimming, but here there are no seas.",
  "My cat sleeps all day and at night she goes crazy and starts running all over the house.",
  "Do you enjoy more action games or mind games? I love both of them.",
  "Why girls hate cargo shorts so much? What is problem with it?",
  "Laziness, lack of motivation, lack of new ideas, lack of creativity... Why these problems are so common nowadays?",
  "I value information which you provide and always find your tips super useful.",
  "I want to buy good traveling bag, any ideas/suggestions? Durability is priority for me.",
  "Singing is not really my thing, my sound is awful and sounds horrible, no living creature can enjoy my singing LOL.",
  "None of my business of course, but you used the wrong details in your article, just wanted to let you know.",
  "The dark mode is more convenient for me, it helps my eyes to relax.",
  "It is quite simple: test all solutions step by step, one of them will work sooner or later.",
  "Did you enjoy latest movie of One Piece? I loved it, so many emotions, so much action and things like that.",
];

module.exports = thoughts;
